#!/bin/bash
#SBATCH --job-name=my_python_job2       # Job name
#SBATCH --output=output2.txt            # Output file
#SBATCH --error=error2.txt              # Error file
#SBATCH --time=48:00:00                # Maximum runtime (hh:mm:ss)
#SBATCH --cpus-per-task=64              # Number of CPU cores per task
#SBATCH --mem=384000                      # Memory per node

# Run Python script
python test-restaurant2.py
